#!/usr/bin/env python3
"""Stage 1 — data preparation and the audit/QC report.

Builds the processed panel (sentinels masked, fold-safe imputation) and writes a
fully numeric data-audit report to ``outputs/reports/data_audit.md``.  Every
number in the report is computed from the data here, not asserted.

Run:  PYTHONPATH=src python3 scripts/01_prepare_data.py
"""
from __future__ import annotations

import sys
import warnings
from pathlib import Path

warnings.filterwarnings("ignore")
sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

import numpy as np
import pandas as pd
from scipy.stats import spearmanr

from thermoroute import config as C
from thermoroute import data as D
from thermoroute import features as F
from thermoroute import results as R


def main() -> None:
    bundle = D.prepare_dataset()
    panel, masks = bundle["panel"], bundle["masks"]
    panel_raw = bundle["panel_raw"]
    clim = F.HarmonicClimatology.fit(panel, masks.train)

    panel.to_parquet(C.DATA_PROCESSED / "panel.parquet")
    print("wrote", C.DATA_PROCESSED / "panel.parquet")

    L = []
    w = L.append
    w("# Data audit & quality-control report — ThermoRoute\n")
    w(f"_Generated by `scripts/01_prepare_data.py`. Stations: "
      f"{', '.join(C.STATIONS)}. Daily records 2006-01-01 → 2020-12-31._\n")

    # 1. coverage
    w("## 1. Coverage and integrity\n")
    w("| station | rows | start | end | duplicate dates | calendar gaps |")
    w("|---|---|---|---|---|---|")
    for st in C.STATIONS:
        sub = panel[panel.site_id == st].sort_values("DATE")
        full = pd.date_range(sub.DATE.min(), sub.DATE.max(), freq="D")
        w(f"| {st} | {len(sub)} | {sub.DATE.min().date()} | {sub.DATE.max().date()} | "
          f"{int(sub.DATE.duplicated().sum())} | {len(full) - len(sub)} |")
    w("")

    # 2. sentinels
    w("## 2. Masked sentinel codes (set to NaN, fold-safe imputed)\n")
    sr = D.sentinel_report()
    w("| station | WDSP=999.9 | PRCP=99.99 |")
    w("|---|---|---|")
    for _, r in sr.iterrows():
        w(f"| {r['site_id']} | {int(r.get('WDSP', 0))} | {int(r.get('PRCP', 0))} |")
    w("\n_These are missing-data codes, never treated as physical extremes._\n")

    # 3. variable summary (raw, post-mask)
    w("## 3. Variable summary (sentinel-masked)\n")
    w("| station | var | mean | std | min | q50 | max |")
    w("|---|---|---|---|---|---|---|")
    for st in C.STATIONS:
        sub = panel_raw[panel_raw.site_id == st]
        for v in C.ALL_VARS:
            s = sub[v]
            w(f"| {st} | {v} | {s.mean():.2f} | {s.std():.2f} | {s.min():.2f} | "
              f"{s.median():.2f} | {s.max():.2f} |")
    w("")

    # 4. seasonal climatology fit
    w("## 4. Harmonic climatology (train-fit) vs persistence\n")
    w("| station | clim RMSE (°C) | WTEMP lag-1 autocorr | persistence RMSE h1/h3/h7 |")
    w("|---|---|---|---|")
    for st in C.STATIONS:
        sub = panel[panel.site_id == st].sort_values("DATE")
        pred = clim.predict_dates(st, sub.DATE)
        crmse = np.sqrt(np.mean((sub.WTEMP.values - pred) ** 2))
        s = sub.WTEMP
        pr = [np.sqrt(np.mean((s.values[h:] - s.values[:-h]) ** 2)) for h in C.HORIZONS]
        w(f"| {st} | {crmse:.3f} | {s.autocorr(1):.3f} | "
          f"{pr[0]:.3f} / {pr[1]:.3f} / {pr[2]:.3f} |")
    w("\n_Persistence is the dominant short-horizon baseline; only damped "
      "persistence toward climatology reliably beats it (see results)._\n")

    # 5. station topology
    w("## 5. Station topology (directed cascade, cross-correlation lags)\n")
    Wp = pd.DataFrame({st: panel[panel.site_id == st].set_index("DATE")["WTEMP"]
                       for st in C.STATIONS})
    Fp = pd.DataFrame({st: panel[panel.site_id == st].set_index("DATE")["FLOW"]
                       for st in C.STATIONS})

    def best_lag(a, b, maxlag=12):
        res = {}
        for Lg in range(maxlag + 1):
            x = a.shift(Lg); m = x.notna() & b.notna()
            res[Lg] = np.corrcoef(x[m], b[m])[0, 1]
        k = max(res, key=res.get)
        return k, res[k]

    w("| pair | FLOW best-lag (d) | FLOW r | WTEMP best-lag (d) | WTEMP r |")
    w("|---|---|---|---|---|")
    for up, dn in [("b1", "s2"), ("s2", "p3"), ("b1", "p3")]:
        lf, rf = best_lag(Fp[up], Fp[dn]); lw, rw = best_lag(Wp[up], Wp[dn])
        w(f"| {up}→{dn} | {lf} | {rf:.3f} | {lw} | {rw:.3f} |")
    w("\n_Confirms b1→s2→p3: flow travels ~1 day per hop; the thermal signal "
      "lags far more to p3 (~9 days), motivating a directed, variable-specific "
      "travel-time prior._\n")

    # 6. rating curve
    w("## 6. Stage–discharge (F–L) rating relationship\n")
    w("| station | spearman(FLOW,WLEVEL) | WLEVEL drift 2006→2020 (m) |")
    w("|---|---|---|")
    for st in C.STATIONS:
        sub = panel[panel.site_id == st]
        rho = spearmanr(sub.FLOW, sub.WLEVEL).statistic
        ym = sub.groupby(sub.DATE.dt.year)["WLEVEL"].mean()
        w(f"| {st} | {rho:.3f} | {ym.iloc[-1] - ym.iloc[0]:+.1f} |")
    w("\n_s2/p3 have near-perfect monotone rating curves (ρ≈0.999); b1 is more "
      "regulated (ρ≈0.82). Multi-year WLEVEL drift ⇒ standardise per station._\n")

    # 7. thresholds
    w("## 7. High-temperature exceedance thresholds (train q90)\n")
    thr = R.exceedance_thresholds(panel, masks)
    w("| station | q90 WTEMP (°C) | n exceed (full record) |")
    w("|---|---|---|")
    for st in C.STATIONS:
        n_ex = int((panel[panel.site_id == st].WTEMP > thr[st]).sum())
        w(f"| {st} | {thr[st]:.1f} | {n_ex} |")
    w("")

    # 8. split + open items
    w("## 8. Leakage-safe split and open verification items\n")
    s = C.SPLIT.as_dict()
    w(f"- **train** {s['train'][0]}…{s['train'][1]} · **val** {s['val'][0]}…{s['val'][1]} "
      f"· **calib** {s['calib'][0]} · **blind test** {s['test'][0]}…{s['test'][1]}")
    w(f"- All scalers, climatology and rating curves are fit on **train only**.")
    w(f"- **DH semantics unverified** (`config.DH_SEMANTICS_VERIFIED="
      f"{C.DH_SEMANTICS_VERIFIED}`): audit is consistent with a sunshine/insolation "
      f"index but a data-dictionary check is required before any DH-based claim.")
    w("")

    out = C.REPORTS / "data_audit.md"
    out.write_text("\n".join(L))
    print("wrote", out, f"({len(L)} lines)")


if __name__ == "__main__":
    main()
