#!/usr/bin/env python3
"""Station-median result tables with cluster-bootstrap inference (P0-3).

Reads the Phase-2 derivation outputs (station metrics, skill table, paired
effects, cluster inference) and renders the paper's held-out tables 4.6-4.8
with the manuscript's own estimator: unweighted station-median RMSE, the
>=100-target reportability rule, and cluster-bootstrap CIs with win rates —
no pooled cells, no "--" uncertainty columns.

Correspondence with paper/agu_submission/ThermoRoute_WRR.tex:
  * Table 4.6 -- paired comparisons (median dRMSE, CI low/high, win rate,
    Holm-adjusted p, n stations / n clusters).
  * Table 4.7 -- primary models, station-median RMSE/MAE/bias + skill vs
    damped persistence + reportable station count.
  * Table 4.8 -- one-factor ablations, same layout.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import pandas as pd

REPO = Path(__file__).resolve().parents[1]
OUT = REPO / "outputs" / "conventional"

PRIMARY_MODELS = ["Persistence", "DampedPersistence", "Climatology",
                  "LightGBM", "LSTM", "ThermoRoute"]
ABLATION_MODELS = ["TR-fixedKappa", "TR-noDynamicPrior", "TR-noMoE",
                   "TR-noRouter", "TR-noTCN", "TR-unbounded"]
HORIZONS = (1, 3, 7)


def load_derivations(base: Path) -> dict[str, pd.DataFrame | dict]:
    station = pd.read_csv(base / "station_metrics_2021_2023.csv")
    skill = pd.read_csv(base / "skill_table_2021_2023.csv")
    effects = pd.read_csv(base / "paired_effects_2021_2023.csv")
    inference = json.loads((base / "cluster_inference_2021_2023.json").read_text())
    return {"station": station, "skill": skill, "effects": effects, "inference": inference}


def station_median_table(station: pd.DataFrame, models: list[str]) -> pd.DataFrame:
    rows = []
    for model in models:
        sub = station[station.model == model]
        for h in HORIZONS:
            gh = sub[sub.horizon == h]
            if gh.empty:
                continue
            rows.append({
                "model": model, "horizon": h,
                "rmse": float(gh.rmse.median()),
                "mae": float(gh.mae.median()),
                "bias": float(gh.bias.median()),
                "n_stations": int(len(gh)),
            })
    return pd.DataFrame(rows)


def skill_vs_damped(skill: pd.DataFrame, model: str, h: int) -> float | None:
    row = skill[(skill.model == model) & (skill.horizon == h)
                & (skill.baseline == "DampedPersistence")]
    if row.empty:
        return None
    return float(row.skill.iloc[0])


def render_tables(data: dict) -> str:
    station = data["station"]
    skill = data["skill"]
    inference = data["inference"]
    lines: list[str] = []
    lines.append("%% Held-out station-median tables with cluster inference (P0-3).")
    lines.append("%% Generated by scripts/build_station_tables.py")
    lines.append("")

    # Table 4.6 -- paired comparisons
    lines.append("\\begin{table}[htbp]")
    lines.append("\\caption{Held-out 2021--2023 paired station-median $\\Delta$RMSE"
                 " (${}^\\circ$C, negative favours the candidate), cluster-bootstrap"
                 " 95\\% CI, win rate and cluster sign-flip $p$ (Holm-adjusted over"
                 " the five-test family).}\n\\label{tab:paired-holdout}\n\\centering")
    lines.append("\\small")
    lines.append("\\begin{tabular}{lcrrrrr}\n\\toprule")
    lines.append("Contrast & $h$ (d) & $\\Delta$RMSE & CI low & CI high & win rate & $p_{holm}$ \\\\")
    lines.append("\\midrule")
    for key in sorted(inference):
        rec = inference[key]
        lines.append(
            f"{rec['candidate']} vs {rec['reference']} & {rec['horizon']} & "
            f"{rec['effect']:.3f} & {rec['ci_low']:.3f} & {rec['ci_high']:.3f} & "
            f"{rec['win_rate']:.2f} & {rec['holm_p']:.3f} \\\\")
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("\\end{table}")
    lines.append("")

    for table_id, title, models in (("4.7", "primary models", PRIMARY_MODELS),
                                    ("4.8", "one-factor ablations", ABLATION_MODELS)):
        med = station_median_table(station, models)
        lines.append("\\begin{table}[htbp]")
        lines.append(f"\\caption{{Held-out 2021--2023 station-median metrics, {title}. "
                     "Median over reportable stations ($\\geq$100 valid paired "
                     "targets per station/lead); skill is $1-\\mathrm{RMSE}/"
                     "\\mathrm{RMSE}_{\\mathrm{damped}}$ on the same station set; "
                     "$n$ is the reportable station count.}}\n"
                     f"\\label{{tab:holdout-{table_id}}}\n\\centering")
        lines.append("\\small")
        lines.append("\\begin{tabular}{lrrrrrr}\n\\toprule")
        lines.append("Model & $h$ (d) & RMSE & MAE & bias & skill vs damped & $n$ \\\\")
        lines.append("\\midrule")
        for _, row in med.iterrows():
            sv = skill_vs_damped(skill, row["model"], int(row["horizon"]))
            skill_txt = "--" if sv is None else f"{sv:.3f}"
            lines.append(
                f"{row['model']} & {int(row['horizon'])} & {row['rmse']:.3f} & "
                f"{row['mae']:.3f} & {row['bias']:+.3f} & {skill_txt} & "
                f"{int(row['n_stations'])} \\\\")
        lines.append("\\bottomrule")
        lines.append("\\end{tabular}")
        lines.append("\\end{table}")
        lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--base", default=OUT, type=Path)
    parser.add_argument("--out", default=OUT / "holdout_station_tables_2021_2023.tex", type=Path)
    args = parser.parse_args(argv)
    data = load_derivations(args.base)
    rendered = render_tables(data)
    args.out.write_text(rendered, encoding="utf-8")
    print(f"wrote {args.out} ({len(rendered)} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
